DROP TABLE IF EXISTS POST;
CREATE TABLE POST (
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  TITLE TEXT NOT NULL,
  BODY TEXT NOT NULL,
  UP_DATE DATETIME NOT NULL,
  CLICKED INTEGER NOT NULL,
  CATEGORY_ID INTEGER NOT NULL ,
    FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORY(ID)
);

DROP TABLE IF EXISTS TAG;
CREATE TABLE TAG (
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  NAME TEXT NOT NULL
);

DROP TABLE IF EXISTS CATEGORY;
CREATE TABLE CATEGORY (
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  NAME TEXT NOT NULL
);

DROP TABLE IF EXISTS TAGS;
CREATE TABLE TAGS(
  ID INTEGER PRIMARY KEY AUTOINCREMENT ,
  TAG_ID INTEGER  ,
  POST_ID INTEGER
);

